root: true

env:
  node: true

parser: vue-eslint-parser

parserOptions:
  parser: '@typescript-eslint/parser'

plugins:
  - 'vue'
  - '@typescript-eslint'

extends:
  - 'plugin:vue/vue3-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - '@nuxtjs'
  - '@nuxtjs/eslint-config-typescript'
  - '@antfu'
  - '@unocss'

rules:
  vue/multi-word-component-names: 'off'
  no-console: warn
