root: true

env:
  es6: true
  node: true
  browser: true

parser: vue-eslint-parser

parserOptions:
  parser: '@typescript-eslint/parser'

plugins:
  - 'vue'
  - 'import'
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - '@nuxtjs'
  - '@nuxtjs/eslint-config-typescript'
  - '@antfu'
  - 'plugin:unocss/recommended'
  - '@unocss'

settings:
  'import/parsers':

  'import/resolver':
    typescript: true
    node: true

rules:
  'no-console': 'warn'
  '@unocss/order': 'error'
  'unocss/classnames-order': 'error'
  'unocss/no-excessive-whitespaces': 'error'
  'unocss/no-duplicated-classnames': 'error'
  'vue/multi-word-component-names': 'off'
  'import/no-unresolved': 'error'
  'import/namespace': 'error'
  'import/default': 'error'
  'import/export': 'error'
  'import/named': 'error'
  'import/order':
    - 'error'
    - 'groups':
      - 'builtin'
      - 'external'
      - 'object'
      - 'parent'
      - 'internal'
      - 'sibling'
      - 'index'
      - 'type'
      'pathGroups':
        - 'pattern': '@/**'
          'group': 'internal'
          'position': 'after'
        - 'pattern': '~/**'
          'group': 'internal'
          'position': 'after'
      'distinctGroup': true
      'newlines-between': 'always'
      'alphabetize':
        'order': 'asc'
        'caseInsensitive': true
