root: true

env:
  node: true

parser: vue-eslint-parser

parserOptions:
  parser: '@typescript-eslint/parser'

plugins:
  - 'vue'
  - '@typescript-eslint'
  - prettier

extends:
  - 'plugin:@typescript-eslint/recommended'
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:vue/vue3-recommended'
  - '@unocss'
  - '@antfu'
  - prettier

rules:
  antfu/generic-spacing: 'off'
  vue/multi-word-component-names: 'off'
  prettier/prettier: warn
  no-console: warn
