import { useStorage } from '@vueuse/core'

import type { ISelection } from '~/types'

export const settingsStoreKey = 'settings' as const

const selections = useStorage<{ selections: ISelection[] }>(
  'selections',
  {
    selections: [],
  },
)

const propertyIcons = useStorage('propertyIcons', {
  iconSize: [50, 64],
  iconAnchor: [25, 64],
  tooltipAnchor: [25, -40],
  popupAnchor: [25, -64],
  iconUrl: 'uncategorized/default.svg',
})

const districtBoundaries = useStorage('districtBoundaries', {
  fillOpacity: 0.05, // прозрачность фона
  fillColor: '#3388ff', // цвет фона
  color: '#3388ff', // цвет границ
  weight: 1, // ширина границ
})

export const useSettingsStore = defineStore('settings', () => {
  const descriptionsIcons = getDescriptionSize()

  return {
    propertyIcons,
    districtBoundaries,
    descriptionsIcons,
    selections,
  }
})

function getDescriptionSize() {
  return {
    uncategorized: {
      'default': 'Пункт управления органа исполнительной власти',
      '1_uncategorized': 'Склады',
      '2_uncategorized':
        'Потенциально опасные объекты экономики, содержащие АХОВ',
      '3_uncategorized': 'Автозаправочная станция',
      '4_uncategorized': 'Аэропорт',
      '5_uncategorized': 'Вертолетные посадочные площадки',
      '6_uncategorized': 'Завод',
      '7_uncategorized': 'Школы',
      '8_uncategorized': 'Образовательные учреждения',
      // '9_uncategorized': '',
      '10_uncategorized': 'Объекты культуры',
      '11_uncategorized': 'Жилищно-коммунальные хозяйства',
      '12_uncategorized': 'Жилищно-коммунальные объекты',
      '13_uncategorized': 'Финансовые организации',
      '14_uncategorized': 'Другие объекты',
      '15_uncategorized': 'Элеваторы и зернохранилища',
      '16_uncategorized': 'Перерабатывающий завод',
      '17_uncategorized': 'Нефтедобывающий завод',
      '18_uncategorized': 'Хлебозаводы и пекарни',
      '19_uncategorized': 'Нефтеперерабатывающий завод',
      '20_uncategorized': 'Мукомольный комбинат',
      '21_uncategorized': 'Нефтебазы и нефтехранилища',
      '22_uncategorized': 'Магазины, рынки',
      '23_uncategorized': 'Котельная',
      '24_uncategorized': 'СЭС',
      '25_uncategorized': 'ТЭЦ',
      '26_uncategorized': 'ВЭС',
      '27_uncategorized': 'ГЭС',
      '28_uncategorized': 'Швейные фабрики и ателье',
      '29_uncategorized': 'Обувные фабрики',
      '30_uncategorized': 'Ферма',
      '31_uncategorized': 'Ремонтный цех, мастерская',
      '32_uncategorized': 'Пивоварни и ликеро-водочные заводы',
      '33_uncategorized': 'Детские сады',
      '34_uncategorized': 'Ясли',
      '35_uncategorized': 'Памятники',
      '36_uncategorized': 'Университеты',
      '37_uncategorized': 'НИИ',
      '38_uncategorized': 'Научные лаборатории',
      '39_uncategorized': 'Транспорт',
      // '40_uncategorized': '',
      'uncategorized/default': 'Пункт управления органа исполнительной власти',
      'uncategorized/1_uncategorized': 'Склады',
      'uncategorized/2_uncategorized':
        'Потенциально опасные объекты экономики, содержащие АХОВ',
      'uncategorized/3_uncategorized': 'Автозаправочная станция',
      'uncategorized/4_uncategorized': 'Аэропорт',
      'uncategorized/5_uncategorized': 'Вертолетные посадочные площадки',
      'uncategorized/6_uncategorized': 'Завод',
      'uncategorized-7_uncategorized/0': 'Школы',
      'uncategorized-8_uncategorized/0': 'Образовательные учреждения',
      // 'uncategorized/9_uncategorized/0': '',
      'uncategorized-10_uncategorized/0': 'Объекты культуры',
      'uncategorized-11_uncategorized/0': 'Жилищно-коммунальные хозяйства',
      'uncategorized-12_uncategorized/0': 'Жилищно-коммунальные объекты',
      'uncategorized-13_uncategorized/0': 'Финансовые организации',
      'uncategorized-14_uncategorized/0': 'Другие объекты',
      'uncategorized-15_uncategorized/0': 'Элеваторы и зернохранилища',
      'uncategorized-16_uncategorized/0': 'Перерабатывающий завод',
      'uncategorized-17_uncategorized/0': 'Нефтедобывающий завод',
      'uncategorized-18_uncategorized/0': 'Хлебозаводы и пекарни',
      'uncategorized-19_uncategorized/0': 'Нефтеперерабатывающий завод',
      'uncategorized-20_uncategorized/0': 'Мукомольный комбинат',
      'uncategorized-21_uncategorized/0': 'Нефтебазы и нефтехранилища',
      'uncategorized-22_uncategorized/0': 'Магазины, рынки',
      'uncategorized-23_uncategorized/0': 'Котельная',
      'uncategorized-24_uncategorized/0': 'СЭС',
      'uncategorized-25_uncategorized/0': 'ТЭЦ',
      'uncategorized-26_uncategorized/0': 'ВЭС',
      'uncategorized-27_uncategorized/0': 'ГЭС',
      'uncategorized-28_uncategorized/0': 'Швейные фабрики и ателье',
      'uncategorized-29_uncategorized/0': 'Обувные фабрики',
      'uncategorized-30_uncategorized/0': 'Ферма',
      'uncategorized-31_uncategorized/0': 'Ремонтный цех, мастерская',
      'uncategorized-32_uncategorized/0': 'Пивоварни и ликеро-водочные заводы',
      'uncategorized-33_uncategorized/0': 'Детские сады',
      'uncategorized-34_uncategorized/0': 'Ясли',
      'uncategorized-35_uncategorized/0': 'Памятники',
      'uncategorized-36_uncategorized/0': 'Университеты',
      'uncategorized-37_uncategorized/0': 'НИИ',
      'uncategorized-38_uncategorized/0': 'Научные лаборатории',
      'uncategorized-39_uncategorized/0': 'Транспорт',
    },
    chs: {
      'blob': 'Водоканал',
      'blob_n': 'Водоканал (2)',
      'fire': 'Потенциально опасные объекты экономики Взрыво-пожароопасные / Пожарная служба',
      'fire_n':
        'Потенциально опасные объекты экономики Взрыво-пожароопасные / Пожарная служба (2)',
      'leaf': 'Природные ресурсы и экология',
      'leaf_n': 'Природные ресурсы и экология (2)',
      'lightning_n': '',
      '1_chs': '',
      '2_chs': '',
      '3_chs': '',
      '4_chs': '',
      '5_chs': '',
      '6_chs': '',
      '7_chs': '',
      '8_chs': '',
      '9_chs': '',
      '10_chs': '',
      '11_chs': '',

      'chs-blob/0': 'Водоканал',
      'chs-blob_n/0': 'Водоканал (2)',
      'chs-fire/0':
        'Потенциально опасные объекты экономики Взрыво-пожароопасные / Пожарная служба',
      'chs-fire_n/0':
        'Потенциально опасные объекты экономики Взрыво-пожароопасные / Пожарная служба (2)',
      'chs-leaf/0': 'Природные ресурсы и экология',
      'chs-leaf_n/0': 'Природные ресурсы и экология (2)',
      'chs-lightning_n/0': 'Электростанции',
      'chs/1_chs': '',
      'chs/2_chs': '',
      'chs/3_chs': '',
      'chs/4_chs': '',
      'chs/5_chs': '',
      'chs/6_chs': '',
      'chs/7_chs': '',
      'chs/8_chs': '',
      'chs/9_chs': '',
      'chs/10_chs': '',
      'chs/11_chs': '',
    },
    connection: {},
    gro: {},
    rzd: {},
    mvd: {},
    sport: {
      'autocamps': 'Авто лагеря',
      'bike': 'Велобазы и прокаты',
      'chess': 'Шахматные и интеллектуальные клубы',
      'games': 'Спортивные и игровые залы',
      'hotels': 'Гостиницы',
      'moto': 'Авто и мото клубы',
      'pools': 'Бассейны',
      'roller': 'Прокаты роликов и коньков',
      'sanatorium': 'Оздоровительные центры',
      'school': 'Школы танцев и хореографические кружки',
      'skis': 'Лыжный прокат',
      'stadiums': 'Стадионы и спортплощадки',
      'tent': 'Палаточный лагерь',
      'training': 'Спортивные объекты и тренажерные залы',
      'travel': 'Санатории, лагеря, базы отдыха',

      'sport-autocamps/0': 'Авто лагеря',
      'sport-bike/0': 'Велобазы и прокаты',
      'sport-chess/0': 'Шахматные и интеллектуальные клубы',
      'sport-games/0': 'Спортивные и игровые залы',
      'sport-hotels/0': 'Гостиницы',
      'sport-moto/0': 'Авто и мото клубы',
      'sport-pools/0': 'Бассейны',
      'sport-roller/0': 'Прокаты роликов и коньков',
      'sport-sanatorium/0': 'Оздоровительные центры',
      'sport-school/0': 'Школы танцев и хореографические кружки',
      'sport-skis/0': 'Лыжный прокат',
      'sport-stadiums/0': 'Стадионы и спортплощадки',
      'sport-tent/0': 'Палаточный лагерь',
      'sport-training/0': 'Спортивные объекты и тренажерные залы',
      'sport-travel/0': 'Санатории, лагеря, базы отдыха',
    },
    medical: {},
    military: {},
    tero: {},
    transport: {
      'bridge': 'Мост',
      'bridge_n': 'Мост (2)',
      'bridge_fire':
        'Места возможных террористических актов с применением взрывных устройств',
      'bridge_out': 'Разрушенный мост',
      'map': 'Карта',
      'motorway': 'Автомагистраль',
      'railway': 'Железная дорога',
      'road': 'Дорога',
      'route': 'Маршрут',
      'repair': 'Места проведения дорожных работ',
      'road_rf': 'Дорожные органы РФ',
      'airfields': 'Аэродромы',
      '1_airfields': 'Гидроаэродром',
      '2_airfields': 'Аэродромы грунтовые',
      '3_airfields': 'Аэродромы третьего класса с ВПП 1200 - 1700 м',
      '4_airfields': 'Аэродромы второго класса с ВПП 1800 - 2400 м;',
      '5_airfields': 'Аэродромы первого класса с ВПП 2500 - 3000 м',
      '6_airfields': 'Аэродромы общего назначения',

      'transport-bridge/0': 'Мост',
      'transport-bridge_n/0': 'Мост (2)',
      'transport/bridge_fire':
        'Места возможных террористических актов с применением взрывных устройств',
      'transport/bridge_out': 'Разрушенный мост',
      'transport-map/0': 'Карта',
      'transport-motorway/0': 'Автомагистраль',
      'transport-railway/0': 'Железная дорога',
      'transport-road/0': 'Дорога',
      'transport-route/0': 'Маршрут',
      'transport/repair': 'Места проведения дорожных работ',
      'transport-road_rf/0': 'Дорожные органы РФ',
      'transport-airfields/0': 'Аэродромы',
      'transport/1_airfields': 'Гидроаэродром',
      'transport/2_airfields': 'Аэродромы грунтовые',
      'transport/3_airfields': 'Аэродромы третьего класса с ВПП 1200 - 1700 м',
      'transport/4_airfields': 'Аэродромы второго класса с ВПП 1800 - 2400 м;',
      'transport/5_airfields': 'Аэродромы первого класса с ВПП 2500 - 3000 м',
      'transport/6_airfields': 'Аэродромы общего назначения',
    },
    other: {
      'business': 'Бизнесцентры',
      'construction': 'Строительные организации',
      'cultural': 'Объекты культуры (2)',
      'material': 'Производство отделочных и строительных материалов',
      'meat': 'Мясокомбинат',
      'money': 'Финансовые организации (2)',
      'rest': 'Пищевая промышленность',
      'roof': 'Другие объекты (2)',
      'school': 'Образовательные учреждения (2)',
      'services': 'Услуги',
      'shop': 'Магазины',

      'other-business/0': 'Бизнесцентры',
      'other-construction/0': 'Строительные организации',
      'other-cultural/0': 'Объекты культуры (2)',
      'other-material/0': 'Производство отделочных и строительных материалов',
      'other-meat/0': 'Мясокомбинат',
      'other-money/0': 'Финансовые организации (2)',
      'other-rest/0': 'Пищевая промышленность',
      'other-roof/0': 'Другие объекты (2)',
      'other-school/0': 'Образовательные учреждения (2)',
      'other-services/0': 'Услуги',
      'other-shop/0': 'Магазины',
    },
  }
}
