version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        NODE_VERSION: '19.5.0'

        INSTALL_ZSH: 'true'
        UPGRADE_PACKAGES: 'true'
        USERNAME: node
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
